//Iniciamos una nueva peticion con los ### los separamos

### 


POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Griselda Tejeda",
    "age": 64,
    "email": "gtejeda@mail.com"
}

### 
GET http://localhost:9000/api/users  HTTP/1.1

###
GET http://localhost:9000/api/users/64a789e4e438a0b4167ef009  HTTP/1.1

###
PUT http://localhost:9000/api/users/64a78a87e438a0b4167ef00b HTTP/1.1
Content-Type: application/json

{
    "name": "Paola Vanesa Torres",
    "age": 42,
    "email": "ptorresv@mail.com"
}


###
DELETE http://localhost:9000/api/users/64a78f9e06f1eb0cb7cefcae  HTTP/1.1

